# Generated by Django 3.1.3 on 2020-11-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshot', '0002_auto_20201128_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='ra',
        ),
    ]
