# Generated by Django 3.1.3 on 2020-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshot', '0003_auto_20201128_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data_cadastro',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_final',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao_atividade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='fontes_atividade',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_atividade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='titulo_atividade',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
