# Generated by Django 3.1.3 on 2020-11-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshot', '0005_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.IntegerField(null=True)),
                ('nome_curso', models.DateField(max_length=30, null=True)),
            ],
        ),
    ]
