# Generated by Django 3.1.3 on 2020-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshot', '0008_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='id_aula',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='matricula_usuario',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='id_curso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='id_materia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_curso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula_responsavel',
            field=models.IntegerField(null=True),
        ),
    ]
