# Generated by Django 3.1.3 on 2020-12-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshot', '0009_auto_20201129_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='id',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='id_atividade',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aula',
            name='id_aula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='id_materia',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome_materia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula_usuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha_usuario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
