# Generated by Django 3.1.3 on 2020-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshot', '0009_auto_20201129_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxUsuarioAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vinculacao', models.IntegerField(null=True)),
                ('matricula_usuario', models.IntegerField(null=True)),
                ('id_aula', models.IntegerField(null=True)),
            ],
        ),
    ]
